<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0;net10.0-android</TargetFrameworks>
    <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
    <Title>Cross platform .NET bindings for SDL3</Title>
    <RootNamespace>SDL</RootNamespace>
    <WarningsAsErrors>true</WarningsAsErrors>
    <IsPackable>true</IsPackable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>3.4.14</VersionPrefix>
    <!--<VersionSuffix>fix1</VersionSuffix>-->
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(RepoRootPath)README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\runtimes\**" PackagePath="runtimes" Pack="true" />
    <EmbeddedJar Include="Jars\SDL3AndroidBridge.jar" />
  </ItemGroup>


</Project>
